server {
    listen 80;
    server_name djangoclickmartsp.online www.djangoclickmartsp.online;
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Frontend (React)
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Backend (Django)
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Django admin & static
    location /admin/ {
        proxy_pass http://backend:8000;
    }

    location /static/ {
        alias /static/;
    }

    location /media/ {
        proxy_pass http://backend:8000;
    }
}
